# See: https://theme-next.js.org/docs/theme-settings/
cache:
  enable: false
minify: true
scheme: Gemini
darkmode: true

favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /manifest.json
  
creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true
  language: zh-CN
  
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  
menu_settings:
  icons: true
  badges: true
  
sidebar:
  position: left
  display: post
  padding: 15
  offset: 12
  
avatar:
  url: #/images/avatar.gif
  rounded: false
  rotated: false
site_state: true

social:
  GitHub: https://github.com/ || fab fa-github
  E-Mail: mailto:ceek@vip.qq.com || fa fa-envelope
  
social_icons:
  enable: true
  icons_only: true
  transition: false
  
links_settings:
  icon: fa fa-globe
  title: Links
  layout: block
  
links:
  #Title: https://example.com
  
toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6
  
chat:
  enable: true
  #service: 
  #service: 
  icon: fa fa-comment # Icon name in Font Awesome, set false to disable icon.
  text: Chat # Button text, change it as you wish.
  
language_switcher: true

footer:
  since: 1998
  icon:
    name: fa fa-heart
    animated: true
    color: "#ff0000"
  copyright:
  
excerpt_description: true
read_more_btn: true

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true
  
symbols_count_time:
  separated_meta: true
  item_text_total: false
tag_icon: true

reward_settings:
  enable: false
  animation: true
  comment: Buy me a coffee
  
reward:
  #wechatpay: /images/wechatpay.png
  #alipay: /images/alipay.png
  #paypal: /images/paypal.png
  #bitcoin: /images/bitcoin.png
  
follow_me:
  #Twitter: https://twitter.com/username || fab fa-twitter
  #Telegram: https://t.me/channel_name || fab fa-telegram
  #WeChat: /images/wechat_channel.jpg || fab fa-weixin
  RSS: /atom.xml || fa fa-rss

related_posts:
  enable: true
  title: # Custom header, leave empty to use the default one
  display_in_home: false
  params:
    maxCount: 5
    #PPMixingRate: 0.0
    #isDate: false
    #isImage: true
    #isExcerpt: false

post_edit:
  enable: true
  url: https://github.com/onocs/onocs.github.io/tree/dev/source/ # Link for view source
  #url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/ # Link for fork & edit

post_navigation: left

tagcloud:
  min: 12 # Minimun font size in px
  max: 30 # Maxium font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order

# Misc Theme Settings
preconnect: true

text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify
  mobile: justify
  
mobile_layout_economy: true

android_chrome_color: "#222"

codeblock:
  theme:
    light: tomorrow
    dark: tomorrow-night
  prism:
    light: prism
    dark: prism-dark
  # Add copy button on codeblock
  copy_button:
    enable: true
    # Available values: default | flat | mac
    style: mac

back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: false

reading_progress:
  enable: false
  # Available values: left | right
  startAt: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 3px

bookmark:
  enable: true
  color: "#222"
  save: auto

github_banner:
  enable: true
  permalink: https://github.com/onocs

# Find fonts on Google Fonts (https://fonts.google.com)
# All fonts set here will have the following styles: light | light italic | normal | normal italic | bold | bold italic
# Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS

font:
  enable: false
  host: http://fonts.loli.net
  global:
    external: true
    family: Lato
    size: 0.8
  title:
    external: true
    family: 
    size: 0.8
  headings:
    external: true
    family:
    size: 0.8
  posts:
    external: true
    family:
  codes:
    external: true
    family: Courier New
    size: 0.5

index_with_subtitle: false
exturl: false
exturl_icon: true

google_site_verification:
bing_site_verification:
yandex_site_verification:
baidu_site_verification:

math:
  every_page: false
  mathjax:
    enable: false
    tags: none

  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false    
pjax: true
fancybox: true
mediumzoom: true
lazyload: true
pangu: true
quicklink:
  enable: false
  home: false
  archive: false
  delay: true
  timeout: 3000
  priority: true
  ignores:


comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default.
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances
  active:
  storage: true
  # Lazyload all comment systems.
  lazyload: true
  # Modify texts or order for any navs, here are some examples.
  nav:
    #disqus:
    #  text: Load Disqus
    #  order: -1
    #gitalk:
    #  order: -2

disqus:
  enable: false
  shortname:
  count: true
  
disqusjs:
  enable: false
  api:
  apikey: # Register new application from https://disqus.com/api/applications/
  shortname: # See: https://disqus.com/admin/settings/general/

changyan:
  enable: true
  appid: cytbQfMsF
  appkey: e6252376611e512ef8df6f1ac6a2fe64

gitalk:
  enable: false
  github_id: # GitHub repo owner
  repo: # Repository name to store issues
  client_id: # GitHub Application Client ID
  client_secret: # GitHub Application Client Secret
  admin_user: # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  proxy: https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token # This is official proxy adress
  language: zh-CN

# Utterances
# For more information: https://utteranc.es
utterances:
  enable: false
  repo: # Github repository name
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: github-light
rating:
  enable: false
  id:     # <app_id>
  color:  "#fc6423"
add_this_id:
baidu_analytics: # <app_id>
growingio_analytics: # <project_id>

cloudflare_analytics:

leancloud_visitors:
  enable: false
  app_id: # <your app id>
  app_key: # <your app key>
  server_url: # <your server url>
  security: true

firestore:
  enable: false
  collection: articles # Required, a string collection name to access firestore database
  apiKey: # Required
  projectId: # Required

busuanzi_count:
  enable: false
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye
  
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: true
  preload: true

chatra:
  enable: false
  async: true
  id: # Visit Dashboard to get your ChatraID
  #embed: # Unfinished experimental feature for developers. See: https://chatra.com/help/api/#injectto

tidio:
  enable: false
  key: # Public Key, get it from dashboard. See: https://www.tidio.com/panel/settings/developer

note:
  style: simple
  icons: false
  light_bg_offset: 0

# Tabs tag
tabs:
  transition:
    tabs: false
    labels: true

pdf:
  enable: true
  # Default height
  height: 500px

# Mermaid tag
mermaid:
  enable: false
  # Available themes: default | dark | forest | neutral
  theme: forest

motion:
  enable: true
  async: false
  transition:
    # All available transition variants: https://theme-next.js.org/animate/
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    # Only for Pisces | Gemini.
    sidebar: fadeInUp

nprogress:
  enable: false
  spinner: true

canvas_ribbon:
  enable: false
  size: 300 # The width of the ribbon
  alpha: 0.6 # The transparency of the ribbon
  zIndex: -1 # The display level of the ribbon


vendors:
  internal: jsdelivr
  plugins: jsdelivr

css: css
js: js
images: images